GET http://localhost:3000/api/fishingdays
###
GET http://localhost:3000/api/fishingdays/6242cce8eaa8b2a66bc44cb5
###
POST http://localhost:3000/api/fishingdays
content-type: application/json

{
  "fish": "Brasse",
  "waters": "Alster"
}
###
DELETE http://localhost:3000/api/fishingdays/6242cce8eaa8b2a66bc44cb5
###
PATCH http://localhost:3000/api/fishingdays/6242cce8eaa8b2a66bc44cb5
content-type: application/json

{
  "fish": "Hecht",
  "waters": "Alster"
}